### ISSUE TITLE
support bpmnjs 6

### ISSUE THREAD

**Issue by evanyangg** [bpmn-io/bpmn-js-cli#6]
requires a peer of bpmn-js@^1.x || ^2.x || ^3.x || ^4.x || ^5.x but none is installed
can you upgrade dependencies, thanks a lot

**Comment by pinussilvestrus** [comment]
Hi, thanks for reporting, I fixed it with https://github.com/bpmn-io/bpmn-js-cli/commit/ec660bf912bd3a240a22498292ecbff1d2612d21
